// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesProjectApi
{
    public partial class OrderItems
    {
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal ItemPrice { get; set; }
        public int Quantity { get; set; }
        public string ItemCategory { get; set; }
        public int Size { get; set; }
        public string Color { get; set; }

        public virtual Orders Order { get; set; }
    }
}